-- ID表
CREATE TABLE TABLE_ID_GEN  (
    GEN_NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs NOT NULL,
    GEN_VAL BIGINT(20) NULL DEFAULT NULL,
    PRIMARY KEY (GEN_NAME) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_as_cs ROW_FORMAT = Dynamic;

-- 用户表
CREATE TABLE USER(
    ID                  BIGINT       NOT NULL COMMENT 'ID',
    ACCOUNT             VARCHAR(255) NOT NULL COMMENT '账号',
    PASS_WORD           VARCHAR(255) NOT NULL COMMENT '密码',
    NAME                VARCHAR(255) NOT NULL COMMENT '名称',
    EMAIL               VARCHAR(255) NULL COMMENT '邮箱',
    TELEPHONE           VARCHAR(255) NULL COMMENT '电话',
    STATUS              INT          NULL COMMENT '状态（0：正常，1：停用，2：注销，3：锁定）',
    ENABLED             INT         NULL COMMENT '是否启用（0：禁用，1：启用）',
    LAST_LOGIN_TIME     BIGINT       NULL COMMENT '最后登录时间',
    CREATOR_ID          BIGINT       NULL COMMENT '创建人ID',
    CREATOR_ACCOUNT     VARCHAR(255) NULL COMMENT '创建人账号',
    CREATOR_NAME        VARCHAR(255) NULL COMMENT '创建人',
    MODIFY_USER_ID      BIGINT       NULL COMMENT '修改人ID',
    MODIFY_USER_ACCOUNT VARCHAR(255) NULL COMMENT '修改人账号',
    MODIFY_USER_NAME    VARCHAR(255) NULL COMMENT '修改人',
    CREATION_TIME       BIGINT       NULL COMMENT '创建时间',
    LAST_MODIFY_TIME    BIGINT       NULL COMMENT '最后修改时间',
    CONSTRAINT PK_USER PRIMARY KEY (ID)
) COMMENT '用户表';

-- 用户扩展表
CREATE TABLE USER_DATE(
    ID      BIGINT       NOT NULL COMMENT 'ID',
    DETAIL  VARCHAR(255) NULL COMMENT '扩展属性',
    CONSTRAINT PK_USER_DATE PRIMARY KEY (ID)
) COMMENT '用户扩展表';
ALTER TABLE USER_DATE
    ADD CONSTRAINT FK_USER_DATE_ON_USER FOREIGN KEY (ID) REFERENCES USER (ID);

-- 角色表
CREATE TABLE ROLE(
    ID                  BIGINT       NOT NULL COMMENT 'ID',
    ROLE_CODE           VARCHAR(255) NOT NULL COMMENT '角色code',
    ROLE_NAME           VARCHAR(255) NOT NULL COMMENT '角色名称',
    ROLE_DESCRIPTION    VARCHAR(255) NULL COMMENT '说明',
    CONSTRAINT PK_ROLE PRIMARY KEY (ID)
) COMMENT '角色表';

-- 角色用户关系表
CREATE TABLE ROLE_USER(
    ID                  BIGINT       NOT NULL COMMENT 'ID',
    ROLE_ID             BIGINT       NOT NULL COMMENT '角色ID',
    USER_ID             BIGINT       NOT NULL COMMENT '用户ID',
    CONSTRAINT PK_ROLE_USER PRIMARY KEY (ID)
) COMMENT '角色用户关系表';
ALTER TABLE ROLE_USER
    ADD CONSTRAINT FK_ROLE_USER_ON_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID);

-- 权限表
CREATE TABLE PERMISSION(
    ID                     BIGINT       NOT NULL COMMENT 'ID',
    PERMISSION_CODE        VARCHAR(255) NOT NULL COMMENT '权限code',
    PERMISSION_NAME        VARCHAR(255) NOT NULL COMMENT '权限名称',
    PERMISSION_DESCRIPTION VARCHAR(255) NULL COMMENT '说明',
    CONSTRAINT PK_PERMISSION PRIMARY KEY (ID)
) COMMENT '权限表';

-- 权限角色关系表
CREATE TABLE PERMISSION_ROLE(
    ID                  BIGINT       NOT NULL COMMENT 'ID',
    PERMISSION_ID       BIGINT       NOT NULL COMMENT '权限ID',
    ROLE_ID             BIGINT       NOT NULL COMMENT '角色ID',
    CONSTRAINT PK_PERMISSION_ROLE PRIMARY KEY (ID)
) COMMENT '权限角色关系表';
ALTER TABLE PERMISSION_ROLE
    ADD CONSTRAINT FK_PERMISSION_ROLE_ON_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION (ID);