-- ID表
DELETE FROM TABLE_ID_GEN;

-- 用户扩展表
DELETE FROM USER_DATE;
-- 用户表
DELETE FROM USER;
-- 角色用户关系表
DELETE FROM ROLE_USER;
-- 角色表
DELETE FROM ROLE;
-- 权限角色关系表
DELETE FROM PERMISSION_ROLE;
-- 权限表
DELETE FROM PERMISSION;
