-- ID表
-- DROP TABLE IF EXISTS TABLE_ID_GEN;

-- 用户扩展表
DROP TABLE IF EXISTS USER_DATE;
-- 用户表
DROP TABLE IF EXISTS USER;
-- 角色用户关系表
DROP TABLE IF EXISTS ROLE_USER;
-- 角色表
DROP TABLE IF EXISTS ROLE;
-- 权限角色关系表
DROP TABLE IF EXISTS PERMISSION_ROLE;
-- 权限表
DROP TABLE IF EXISTS PERMISSION;
