server:
  port: 8089
  servlet:
    context-path: /startblog
spring:
  datasource:
    username: startblog
    password: startblog
    url: jdbc:mysql://192.168.4.5:3306/startblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.zaxxer.hikari.util.DriverDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  #thymeleaf:
  #cache: false
    #encoding: utf-8
thymeleaf:
  prefix:
    classpath: /templates/
url:
  rest:
    prefix:
        v1:/api
allowed.origin.path: http://127.0.0.1:8088